trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

container: ubuntu:18.04

steps:
- script: |
    sudo apt-get -y -qq update
    sudo apt-get -y -qq install \
      --no-install-recommends \
      cmake \
      extra-cmake-modules \
      ninja-build \
      qt5-default \
      libqt5webkit5-dev \
      libqt5x11extras5-dev \
      libarchive-dev \
      libsqlite3-dev \
      libxcb-keysyms1-dev
  displayName: Install dependencies and tools

- script: mkdir build
  displayName: Create build directory

- script: |
    cmake $(Build.Repository.LocalPath) \
      -G ninja
      # -DZEAL_PORTABLE_BUILD="${ZEAL_PORTABLE_BUILD}"
  displayName: Configure project with CMake
  workingDirectory: build

- script: ninja
  displayName: Build
  workingDirectory: build
